spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db   # changed from mysql â†’ localhost
    username: root
    password: 8001323291
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka   # changed from eurekaservice
    register-with-eureka: true
    fetch-registry: true

feign:
  hystrix:
    enabled: true
